export const LOAD_COINS = "LOAD_COINS";
export const FETCH_COINS_SUCCESS = "FETCH_COINS_SUCCESS";
export const FETCH_COIN_SUCCESS = "FETCH_COIN_SUCCESS";
export const FETCH_COIN_HISTORY_SUCCESS = "FETCH_COIN_HISTORY_SUCCESS";
export const FETCH_COIN_INFO_SUCCESS = "FETCH_COIN_INFO_SUCCESS";